const STICKERS = {
  healingVolando: 'assets/stickers/healing-volando.png',
  healingNormal: 'assets/stickers/healing-normal.png',
  healingshy: 'assets/stickers/timido.png',
  healingTimido: 'assets/stickers/healing-timido.png',
  healingPensando: 'assets/stickers/healing-pensando.png',
  healingIzquierda: 'assets/stickers/healing-izquierda.png',
  healingDerecha: 'assets/stickers/healing-derecha.png',
  healingTociendo: 'assets/stickers/healing-tociendo.png',
  healingAsustado: 'assets/stickers/healing-asustado.png',
  healingAsustadoIzquierda: 'assets/stickers/healing-asustado-izquierda.png',
  healingAsustadoDerecha: 'assets/stickers/healing-asustado-derecha.png',
  healingLeyendo: 'assets/stickers/healing-leyendo.png',
  healingSonrojado: 'assets/stickers/healing-sonrojado.png',
  healingVueltaDer: 'assets/stickers/healing-vuelta-der.png',
  healingVueltaIzq: 'assets/stickers/healing-vuelta-izq.png',
  healingGritando: 'assets/stickers/healing-gritando.png',
  healingRecordando: 'assets/stickers/healing-recordando.png',
  healingllamando: 'assets/stickers/healing-llamando.png',
  healingAmor: 'assets/stickers/healing-amor.png',
  healingApuntando: 'assets/stickers/healing-apuntando.png',
  healingPuchero: 'assets/stickers/healing-puchero.png',
  healingLanzandoRegalo: 'assets/stickers/healing-lanzando-regalo.png',

  regalo: 'assets/stickers/regalo.png',
  regaloMeteoro: 'assets/stickers/regalo-meteoro.png',
  regaloImpacto: 'assets/stickers/regalo-impacto.png',
  regaloAura: 'assets/stickers/regalo-aura.png'
};

const scenes = [
  { text: 'tap!', healing: null, gift: null, action: 'idle' },
  { text: '...', healing: null, gift: null, action: 'idle' },
  { text: '...', healing: null, gift: null, action: 'idle' },

  { text: '¡Fiiiuuu…!', healing: STICKERS.healingVolando, gift: null, action: 'entrance' },
  { text: 'hellooo', healing: STICKERS.healingNormal, gift: null, action: 'shy' },
  { text: 'Let’s see... what was I supposed to do?', healing: STICKERS.healingPensando, gift: null, action: 'idle' },
  { text: 'Oh! oki…', healing: STICKERS.healingNormal, gift: null, action: 'idle' },
  { text: '¡Ahem!', healing: STICKERS.healingTociendo, gift: null, action: 'coughBounce' },

  { text: 'Under this soft snow...', healing: STICKERS.healingDerecha, gift: null, action: 'talkFly' },
  { text: 'where dreams sleep in silence...', healing: STICKERS.healingIzquierda, gift: null, action: 'talkFly' },
  { text: 'I, Healing, have come to...', healing: STICKERS.healingDerecha, gift: null, action: 'talkFly' },

  { text: '...', healing: STICKERS.healingPensando, gift: null, action: 'moveLeftSafe' },
  { text: 'Wait... what came next?', healing: STICKERS.healingPensando, gift: null, action: 'leftThinking' },

  { text: 'I was supposed to...', healing: STICKERS.healingPensando, gift: STICKERS.regaloMeteoro, action: 'giftFall' },
  { text: '¡¡PAAAFAM!!', healing: STICKERS.healingAsustado, gift: STICKERS.regaloImpacto, action: 'giftImpact' },
  { text: 'what the heck is that', healing: STICKERS.healingAsustado, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'I mean- oh no! that almost killed me', healing: STICKERS.healingRecordando, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'Ehhh...? What is that?', healing: STICKERS.healingAsustado, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'Eh?', healing: STICKERS.healingAsustadoIzquierda, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'Eeh?', healing: STICKERS.healingAsustadoDerecha, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'Eeeh?', healing: STICKERS.healingAsustadoIzquierda, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'Eeeeh…?', healing: STICKERS.healingAsustadoDerecha, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'well...', healing: STICKERS.healingNormal, gift: STICKERS.regalo, action: 'giftGround' },
  { text: 'you’re all alone huh?', healing: STICKERS.healingRecordando, gift: STICKERS.regalo, action: 'leftThinking' },
  { text: 'lemme see', healing: STICKERS.healingLeyendo, gift: STICKERS.regalo, action: 'approachGift' },
  { text: 'it says f-for you', healing: STICKERS.healingLeyendo, gift: STICKERS.regalo, action: 'readNearGift' },
  { text: 'which means for me!', healing: STICKERS.healingVueltaIzq, gift: STICKERS.regalo, action: 'readNearGift' },
  { text: 'hmmm…', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'returnLeft' },
  { text: '...For me?', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'leftThinking' },
  { text: 'I wonder who it could be from', healing: STICKERS.healingSonrojado, gift: STICKERS.regalo, action: 'blushThinking' },
  { text: 'N-no way...', healing: STICKERS.healingAmor, gift: STICKERS.regalo, action: 'leftThinking' },
  { text: 'W-what s-should I do???', healing: STICKERS.healingSonrojado, gift: STICKERS.regalo, action: 'blushThinking' },
  { text: 'aii hihi', healing: STICKERS.healingSonrojado, gift: STICKERS.regalo, action: 'blushThinking' },

  
  { text: '“For me...”', healing: STICKERS.healingVueltaIzq, gift: STICKERS.regalo, action: 'dilemmaFly' },
  { text: '“maybe...”', healing: STICKERS.healingVueltaDer, gift: STICKERS.regalo, action: 'dilemmaFly' },
  { text: '“For me...”', healing: STICKERS.healingSonrojado, gift: STICKERS.regalo, action: 'dilemmaFly' },
  { text: '“For you...”', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'dilemmaFly' },
  { text: '“For me...”', healing: STICKERS.healingNormal, gift: STICKERS.regalo, action: 'dilemmaFly' },
  { text: '“ah no!”', healing: STICKERS.healingTimido, gift: STICKERS.regalo, action: 'dilemmaFly' },

  { text: 'hmmm…', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'stillLeft' },
  { text: 'There was something I had to do with this...', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'stillLeft' },
  { text: 'I think this was part of the…', healing: STICKERS.healingPensando, gift: STICKERS.regalo, action: 'stillLeft' },

  { text: 'Aaaa... I can’t remember', healing: STICKERS.healingGritando, gift: STICKERS.regalo, action: 'frustratedShout' },
  { text: '...', healing: STICKERS.healingNormal, gift: STICKERS.regalo, action: 'stillLeft' },
  { text: '...oh', healing: STICKERS.healingRecordando, gift: STICKERS.regalo, action: 'realize' },
  { text: 'I had to deliver it.', healing: STICKERS.healingRecordando, gift: STICKERS.regalo, action: 'realize' },
  { text: 'ơiii!', healing: STICKERS.healingllamando, gift: STICKERS.regalo, action: 'pointing' },
  { text: 'you!', healing: STICKERS.healingApuntando, gift: STICKERS.regalo, action: 'pointing' },
  { text: 'y-y-y-you!', healing: STICKERS.healingApuntando, gift: STICKERS.regalo, action: 'pointing' },
  { text: 'I ruined everything soorry ', healing: STICKERS.healingshy, gift: STICKERS.regalo, action: 'pointing' },
  { text: 'sooo… what even is this anyway huh?', healing: STICKERS.healingRecordando, gift: STICKERS.regalo, action: 'realize' },
  { text: 'argh!', healing: STICKERS.healingGritando, gift: STICKERS.regalo, action: 'frustratedShout' },
  { text: 'I thought it was for me...', healing: STICKERS.healingPuchero, gift: STICKERS.regalo, action: 'poutEnvy' },
  { text: 'Hmpf! I wanted one too', healing: STICKERS.healingPuchero, gift: STICKERS.regalo, action: 'poutEnvy' },
  { text: 'But well… I guess today…', healing: STICKERS.healingPuchero, gift: STICKERS.regalo, action: 'poutEnvy' },
  { text: '…is your special day', healing: STICKERS.healingVueltaIzq, gift: STICKERS.regalo, action: 'poutEnvy' },
  { text: 'I should…', healing: STICKERS.healingNormal, gift: STICKERS.regalo, action: 'poutEnvy' },
  { text: 'lemme bring the gift closer to you', healing: STICKERS.healingLanzandoRegalo, gift: STICKERS.regalo, action: 'finalGiftCenter' },
  { text: '“healing used his tiny little power”', healing: STICKERS.healingLanzandoRegalo, gift: STICKERS.regaloAura, action: 'finalGiftGrow' }
];
